[package]
name = "ocean-xyz-account"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12", features = ["json", "gzip", "brotli", "deflate", "blocking"] }
tokio = { version = "1", features = ["full"] }
anyhow = "1"
csv = "1"
serde = { version = "1", features = ["derive"] }